const ActionType = {
  GET_OFFERS: `GET_OFFERS`,
  GET_CURRENT_CITY: `GET_CURRENT_CITY`,
  GET_CURRENT_OFFER: `GET_CURRENT_OFFER`,
  GET_HOVERED_OFFER: `GET_HOVERED_OFFER`,
  REMOVE_HOVERED_OFFER: `REMOVE_HOVERED_OFFER`,
  SET_OFFER_STATUS: `SET_OFFER_STATUS`,
  SET_DEFAULT_ORDER_OFFERS: `SET_DEFAULT_ORDER_OFFERS`,
  SET_LOW_TO_HIGH_ORDER_OFFERS: `SET_LOW_TO_HIGH_ORDER_OFFERS`,
  SET_HIGH_TO_LOW_ORDER_OFFERS: `SET_HIGH_TO_LOW_ORDER_OFFERS`,
  SET_TOP_RATED_FIRST_ORDER_OFFERS: `SET_TOP_RATED_FIRST_ORDER_OFFERS`,
};

export default ActionType;


